### ISSUE TITLE
Redmi Note 11 4G 的代号似乎有误

### ISSUE THREAD

**Issue by tofarfar** [HegeKen/MRData#2]
Hi，Redmi Note 11 4G 的代号[似乎是 selenes](https://xiaomirom.com/rom/redmi-note-11-4g-selenes-china-fastboot-recovery-rom/)，但是[写成了 selene](https://github.com/HegeKen/MRData/blob/master/data/devices/selene.json#L2)，selene [应该只是](https://xiaomirom.com/series/selene/) Redmi 10 的代号，麻烦看看哈！

<img width="1143" alt="截屏2024-03-03 11 22 11" src="https://github.com/HegeKen/MRData/assets/6022398/43ed6063-66e8-4659-8fb8-cd29fbab0f0b">

**Comment by HegeKen** [comment]
这俩机器后来合并发包了，我个人觉得没必要分开，所以就没单独弄。

**Comment by tofarfar** [comment]
哦哦，原来如此！
